apiRules:
- include:
    uidRegex: ^OmiyaGames\.MVC$
    type: Namespace
- include:
    uidRegex: ^OmiyaGames\.MVC\.Editor$
    type: Namespace
- exclude:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace